### ISSUE TITLE
请求开启github pages

### ISSUE THREAD

**Issue by GalvinGao** [BYTEGOING/MyLife-Website#4]
（因为我没有权限，你是owner所以需要你来弄、）为了预览方便，请到 Settings标签往下滑，找到 github pages然后有个branch，选定master之后点save就好 这样就可以预览了 更加方便～ 以后可以直接在 https://bytegoing.github.io/MyLife-Website 进行预览～ @BYTEGOING

**Comment by BYTEGOING** [comment]
刚打算弄...
